### PR TITLE
Fix typos in booktitle/author

### PR DESCRIPTION
**Pull request by enricoschumann**
Hi,

I fixed just the name of a book and an author in the task view.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Uh-oh. Pretty embarrassing on both counts.  Will merge and propagate to Achim's repo.

**Comment by enricoschumann** [comment]
On Tue, 21 Feb 2017, Dirk Eddelbuettel writes:

> Uh-oh. Pretty embarrassing on both counts.  Will merge and propagate to Achim's repo.

thanks!

**Comment by eddelbuettel** [comment]
You should still submit an abstract for R/Finance 2017 and swing by lovely Chicago in May!

**Comment by enricoschumann** [comment]
If I could, I would. But I can't, unfortunately.

**Pull request merged**
